Krukov/cashews

cashews/wrapper.py

add support for redis over TLS

---

cashews/__init__.py
cashews/backends/redis/backend.py
cashews/formatter.py
cashews/helpers.py
cashews/key.py
cashews/serialize.py
cashews/validation.py
tests/test_key.py
tests/test_wrapper.py

Lower keys issue

---

Readme.md
cashews/backends/diskcache.py
cashews/backends/interface.py
cashews/backends/memory.py
cashews/backends/redis/backend.py
cashews/wrapper.py
tests/test_wrapper.py

related to https://github.com/Krukov/cashews/pull/64

add wrapper proxy for get match method

---

cashews/serialize.py
tests/test_serialize.py

Issue https://github.com/Krukov/cashews/issues/59

feat: unpickle bytes if "hash_key" is not used

---

.gitignore
cashews/serialize.py
setup.cfg
tests/test_pickle_serializer.py
tests/test_serialize.py
tox.ini

https://github.com/Krukov/cashews/issues/74

fix serialization for no hash and value with underscore

---

cashews/backends/client_side.py
cashews/backends/diskcache.py
cashews/backends/interface.py
cashews/backends/memory.py
cashews/backends/redis/backend.py
cashews/backends/redis/client.py
cashews/decorators/bloom.py
cashews/decorators/cache/defaults.py
cashews/decorators/cache/soft.py
cashews/decorators/rate.py
cashews/disable_control.py
cashews/formatter.py
cashews/serialize.py
cashews/validation.py

Since the amount of work is too huge for reviewing, I will do the work in multiple steps. This is part 1.
I did here the most simplest and fastest type hints. There are still many places that require to think about before implementing.

feat: update/add/fix type hints

---

Readme.md
cashews/__init__.py
cashews/backends/diskcache.py
cashews/backends/interface.py
cashews/backends/memory.py
cashews/backends/redis/backend.py
cashews/backends/redis/client_side.py
cashews/backends/transaction.py
cashews/decorators/cache/fail.py
cashews/serialize.py
cashews/wrapper/__init__.py
cashews/wrapper/commands.py
cashews/wrapper/decorators.py
cashews/wrapper/disable_control.py
cashews/wrapper/transaction.py
cashews/wrapper/wrapper.py
examples/cache_decorators.py
tests/conftest.py
tests/test_backend.py
tests/test_blooms.py
tests/test_cache.py
tests/test_client_side_cache.py
tests/test_disable_control.py
tests/test_invalidate.py
tests/test_middleware.py
tests/test_transaction.py
tests/test_wrapper.py

https://github.com/Krukov/cashews/issues/115

add transaction feature

---

cashews/formatter.py
tests/test_tags_feature.py

fix https://github.com/Krukov/cashews/issues/130

make parameter in tag template optional

---

cashews/backends/interface.py
tests/test_lock_decorator.py

Solving https://github.com/Krukov/cashews/discussions/129#discussion-4991013

add wait for lock context manager

---

cashews/validation.py
cashews/wrapper/commands.py
cashews/wrapper/tags.py
cashews/wrapper/transaction.py
setup.cfg
tests/test_tags_feature.py
tests/test_wrapper.py

https://github.com/Krukov/cashews/issues/135

fix init tags backend before call it

---

cashews/formatter.py
tests/test_key.py

Solve https://github.com/Krukov/cashews/issues/138

use raw object in template functions

---

cashews/__init__.py

add cache to import all

---

Readme.md
cashews/__init__.py
cashews/contrib/fastapi.py
cashews/formatter.py
cashews/key.py
cashews/key_context.py
cashews/validation.py
cashews/wrapper/tags.py
tests/test_key.py
tests/test_tags_feature.py

https://github.com/Krukov/cashews/issues/185

key context

---

cashews/backends/redis/backend.py
tests/conftest.py

Fix for https://github.com/Krukov/cashews/issues/209

fix: do not close redis

---

cashews/contrib/fastapi.py
tox.ini

fix for https://github.com/Krukov/cashews/issues/219

fix: use seconds for default value in cache_control_ttl

---

cashews/backends/memory.py
cashews/backends/redis/client_side.py
cashews/utils/_bitarray.py
cashews/utils/_bitarray_lib.py
tests/test_backend_commands.py

Fix for https://github.com/Krukov/cashews/issues/210

fix: Copy object on set with mem backend

---

Readme.md
cashews/contrib/fastapi.py

Fix for https://github.com/Krukov/cashews/issues/218

fix: use prefix with etag middleware

---

cashews/backends/redis/client_side.py
tests/test_client_side_cache.py
tests/test_settings_url.py

Fixes https://github.com/Krukov/cashews/issues/238.

Dedicated Redis Client Side Listen Timeout

---

cashews/helpers.py
tests/test_add_prefix.py
tests/test_middleware.py

Fix for https://github.com/Krukov/cashews/issues/251

fix: check DELETE_MANY cmd in midlewares to reformat keys

---

cashews/contrib/_starlette.py
cashews/decorators/cache/iterator.py
cashews/serialize.py
tests/test_cache_exception.py
tests/test_intergations/test_fastapi.py
tests/test_iterators_cache.py

fix for https://github.com/Krukov/cashews/issues/246

Fix iterator on error

---

Readme.md
cashews/picklers.py
tests/test_pickle_serializer.py

feat: json serialization #211

---

cashews/decorators/cache/early.py
cashews/decorators/cache/fail.py
cashews/decorators/cache/hit.py
cashews/decorators/cache/iterator.py
cashews/decorators/cache/simple.py
cashews/decorators/cache/soft.py
cashews/wrapper/decorators.py
tests/test_cache.py
tests/test_transaction.py

fix for issue https://github.com/Krukov/cashews/issues/265

Handle background update in a right way and add an option to control it

---

cashews/wrapper/commands.py
tests/test_backend_commands.py

Fix for https://github.com/Krukov/cashews/issues/266

fix get_or_set for coro default

---

cashews/contrib/fastapi.py
examples/starlette_etag.py
tests/test_intergations/test_fastapi.py

PR for: https://github.com/Krukov/cashews/issues/318

fix: etag middleware adjustments and double quotes
